AJ 813 - Add python client documentation
DataBiosphere/terra-workspace-data-service pull request #182
Opened 2023-03-03 20:39 UTC by yuliadub

I figured out that just in the same way that we generate the python client, we can also generate the docs for the client based on the yaml as well - I think this is helpful since this way it is easy for people to navigate to and see all functionality of the client. We in theory could regenerate this definition with each client change, but would need to understand how that flow would work. First though, it would make sense to decide if that makes sense - to me is seems better then having to manually remember to update, but if the client wont change a whole lot maybe the not highest priority work. 

still working on a few things but this is ready for a first look and any feedback is very welcome!

2023-03-03 20:57 UTC, aaronkanzer commented on docs/WDS Python Client.md
> +Replace env with "dev" or "prod", based on where your workspace is running. Workspace Id can be located either on the Data tab by clinking "data table status" or from the following env variable in th
`clicking` not `clinking` 🥂

2023-03-03 21:02 UTC, aaronkanzer commented on docs/swagger-gen-docs/README.md
> +## Author
Don't forget to give yourself credit! :D

2023-03-03 21:03 UTC, aaronkanzer commented on docs/swagger-gen-docs/README.md
> +# See configuration.py for a list of all supported configuration parameters.
Where might we find the `configuration.py`?

2023-03-03 21:03 UTC, aaronkanzer commented on docs/swagger-gen-docs/README.md
> +# Defining the host is optional and defaults to http://..
Why might I need to alter this value?

2023-03-03 21:03 UTC, aaronkanzer commented on docs/swagger-gen-docs/README.md
> +        pprint(api_response)
`print` not `pprint`

2023-03-03 21:04 UTC, aaronkanzer commented on docs/swagger-gen-docs/README.md
> + All endpoints do not require authorization.
Is this true?

2023-03-06 23:56 UTC, yuliadub commented on docs/swagger-gen-docs/README.md
> +# See configuration.py for a list of all supported configuration parameters.
it would be in the actual files that come with the client - only way to look at it would be pip install and then do a pip show of the path where wds_client was installed.

2023-03-06 23:56 UTC, yuliadub commented on docs/swagger-gen-docs/README.md
> +# Defining the host is optional and defaults to http://..
this would need to be set to the WDS proxy url, it needs to be set before the client can be used. Since this file is auto generated I am not sure I could add that distinct details in there

2023-03-06 23:57 UTC, yuliadub commented on docs/swagger-gen-docs/README.md
> +        pprint(api_response)
not sure why its defaulting to that (again, auto generated by "openapi-generator-client generate")  ...have spent most of the day trying to figure it out and nothing :D

2023-03-06 23:58 UTC, yuliadub commented on docs/swagger-gen-docs/README.md
> + All endpoints do not require authorization.
it is not, but openapi-generator-client thinks so. trying to figure out how to change or exclude this section and no luck so far

2023-03-07 21:43 UTC, bethsheets requested changes
Looks good! I have a few suggestions. Thanks!

2023-03-07 21:43 UTC, bethsheets commented on docs/WDS Python Client.md
> +General WDS Info client allows to check the version of WDS that is running in a given workspace. It can also check the status of WDS, as well as its subcomponents.
suggest - "General WDS Info client checks the version of WDS that is running"

2023-03-07 21:43 UTC, bethsheets commented on docs/WDS Python Client.md
> +### Records
Should we define "Record" vs "recordtype" vs schema? I am a little confused by the terminology. 

In WDS, a record is a row of a data table, and a recordtype is the name of the data table. Is recordtype is same as schema?

2023-03-07 21:55 UTC, yuliadub commented on docs/WDS Python Client.md
> +This will provide a link and a code that one can visit in a browser to log in. Use the same account to authenticate with that you would lob into azure to view the subscription of where your Terra bil
that is a great question - I checked and all of you do have direct subscription access, at least in dev. Not sure if that is by design or part of testing, but in theory it can be possible/granted by the owner of the subscription.

2023-03-07 22:01 UTC, yuliadub commented on docs/WDS Python Client.md
> +### Records
I added a few clarifications in the Records and Shema sections, let me know if that helps!

2023-03-07 22:02 UTC, yuliadub commented
@aaronkanzer resolved your comments for now but will make sure to add them to the task I created for the auto gen doc tracking!

2023-03-08 14:01 UTC, aaronkanzer commented on docs/WDS Python Client.md
> +az login --use-device-code
Perhaps we should mention for now that `WDS` is only supported for `Azure` workspaces then?

2023-03-08 14:03 UTC, aaronkanzer commented on docs/WDS Python Client.md
> +To authenticate your user entity to access a WDS data table, you must have permission to access the workspace where the data table is stored.
Do I have to have any access to the WDS table, or `Reader`, `Writer`, `Owner`, etc?

2023-03-08 14:04 UTC, aaronkanzer commented on docs/WDS Python Client.md
> +WDS endpoint URL can be acquired from Leo APIs and should soon be available in a environmental variable in the notebook VM.
Is Leo a DSP-internal term? I might suggest just explaining what it is if these docs are somewhat external

2023-03-08 14:05 UTC, aaronkanzer commented on docs/WDS Python Client.md
> +def get_wds_url(workspaceId):
Just a thought, but should we make this a utility function somewhere in the `wds-client` package?

2023-03-08 15:03 UTC, davidangb commented on docs/swagger-gen-docs/README.md
> +        pprint(api_response)
why not `pprint`, though? `pprint` would result in much nicer formatting when outputting objects.
https://amalgjose.com/2021/05/09/what-is-the-difference-between-print-and-pprint-in-python/

2023-03-08 15:04 UTC, davidangb commented on docs/swagger-gen-docs/README.md
> + All endpoints do not require authorization.
this is true as far as our openapi definition goes, and therefore as far as any generated client thinks. All our auth is implemented in the relay listener, above/outside of WDS.

Note: this will change as of #183 and future PRs, but as of this writing it is true

2023-03-08 15:11 UTC, davidangb commented on docs/WDS Python Client.md
> +To authenticate your user entity to access a WDS data table, you must have permission to access the workspace where the data table is stored.
not as of this writing. AJ-666 and AJ-667 will be the first tickets where this becomes true (and has Leo-level multi-user apps as a prerequisite)

2023-03-08 15:14 UTC, davidangb commented on docs/WDS Python Client.md
> +WDS endpoint URL can be acquired from Leo APIs and should soon be available in a environmental variable in the notebook VM.
nit: I believe it is "environment" variable, not "environmental" variable

2023-03-08 15:19 UTC, davidangb commented on docs/WDS Python Client.md
> +WDS endpoint URL can be acquired from Leo APIs and should soon be available in a environmental variable in the notebook VM.
thinking out loud: I am not convinced we should/will be able to add the WDS endpoint URL as an environment variable in the notebook.

The logic to determine which WDS app is the correct one is simple in the most common cases, but also has a lot of edge cases. What if the first WDS app errored out and the user deployed a second one? And so forth.

In this doc, I might sidestep it entirely, and say something generic like "find the WDS app in the list of apps that Leo returns, then take its `proxyUrls.wds` value.`

2023-03-08 15:21 UTC, davidangb commented on docs/WDS Python Client.md
> +However, if for some reason it is not, or you are looking to write data into a different workspace data table that you also have access to (remember this will only work if the token you generated has
what does "a different workspace data table that you also have access to" mean here? I don't understand this use case.

2023-03-08 15:22 UTC, davidangb commented on docs/WDS Python Client.md
> +wds_url = response[0]['proxyUrls']['wds']
as discussed in the previous comment, using `[0]` to grab the first app in the response is not going to be correct in all cases.

2023-03-08 15:25 UTC, davidangb commented on docs/WDS Python Client.md
> +api_client.configuration.host = wds_url
thinking out loud: when we get to AJ-879 check here to see if a `api_client.configuration.httpUserAgent ` setting exists (or similar, I don't know the exact name)

2023-03-08 15:27 UTC, davidangb commented on docs/WDS Python Client.md
> +General WDS Info client checks the version of WDS that is running.
nit:
``` suggestion
General WDS Info client checks the version and current status of WDS.
```

2023-03-08 15:29 UTC, davidangb commented on docs/WDS Python Client.md
> +
nit: add code comment e.g.
```suggestion

# this returns the current status of WDS; if WDS is down it indicates where
# the underlying failure may be
```

2023-03-08 15:31 UTC, davidangb commented on docs/WDS Python Client.md
> +tsv_file_name = "TestType_uploaded".tsv";
nit: think you have an extra quote in there:
```suggestion
tsv_file_name = "TestType_uploaded.tsv";
```

2023-03-08 15:34 UTC, davidangb commented on docs/WDS Python Client.md
> +# get data specifics for a specific data set vs all
```suggestion
# get data specifics for a specific table
```

2023-03-08 15:34 UTC, davidangb commented on docs/WDS Python Client.md
> +# get workspace data specifics, such as what records exist
```suggestion
# get workspace data specifics, such as what tables exist

```

2023-03-08 15:35 UTC, davidangb commented on docs/WDS Python Client.md
> +Currently WDS only supports a single WDS instance by workspace, however in the future there will be support for multiple instances per workspace and these functions will be helpful on checking the st
```suggestion
Currently the Terra UI only supports a single WDS instance per workspace, however in the future there will be support for multiple instances per workspace and these functions will be helpful on checking the state of running WDS instances. 
```

2023-03-08 15:41 UTC, aaronkanzer commented on docs/swagger-gen-docs/README.md
> +        pprint(api_response)
Wow ha I didn't know of `pprint`, but that is awesome! I'd prefer to use that for sure

2023-03-08 18:23 UTC, yuliadub commented on docs/WDS Python Client.md
> +az login --use-device-code
great point! added this right at the top

2023-03-08 18:32 UTC, yuliadub commented on docs/swagger-gen-docs/README.md
> +        pprint(api_response)
wow I also didnt know! Thanks for the context David!

2023-03-09 18:03 UTC, yuliadub commented on docs/WDS Python Client.md
> +However, if for some reason it is not, or you are looking to write data into a different workspace data table that you also have access to (remember this will only work if the token you generated has
after chatting more, removing this for now as it is more of an "advanced used scenario"

2023-03-09 18:04 UTC, yuliadub commented on docs/WDS Python Client.md
> +WDS endpoint URL can be acquired from Leo APIs and should soon be available in a environmental variable in the notebook VM.
renamed and added a link to the repo that has a link to swagger - let me know if this looked better!

2023-03-09 18:04 UTC, yuliadub commented on docs/WDS Python Client.md
> +To authenticate your user entity to access a WDS data table, you must have permission to access the workspace where the data table is stored.
after chatting with David more, took away this for now - only leaving instructions around authenticating as notebook identity

2023-03-10 15:41 UTC, yuliadub commented on docs/WDS Python Client.md
> +wds_url = response[0]['proxyUrls']['wds']
let me know if this is what you were thinking?

2023-03-10 18:33 UTC, jordansafer approved these changes

2023-03-10 18:33 UTC, jordansafer commented on docs/WDS Python Client.md
> +To authenticate inside a notebook in Terra, leveraging the managed identity the notebook is running under the following commands need to be executed. These commands will acquire a token that will be
small nit! Can the first sentence be a little simpler or 2 sentences? I don't totally follow, I think the idea is we need to run these commands from the notebook to get the managed identity?

2023-03-10 18:56 UTC, merged