AJ-961 - Insert schema record into sys_wds vs updating
DataBiosphere/terra-workspace-data-service pull request #310
Opened 2023-07-18 21:40 UTC by yuliadub

Slight change from ealier behavior where we were still copying sys-wds over - now that we are not, when we alter schema name, we need to insert schema record  (that UI uses to display tables) into sys_wds.instances. 

Tested in a BEE and cloning works!!! 

Reminder:

PRs merged into main will not automatically generate a PR in https://github.com/broadinstitute/terra-helmfile to update the WDS image deployed to kubernetes - this action will need to be triggered manually by running the following github action: https://github.com/DataBiosphere/terra-workspace-data-service/actions/workflows/tag.yml. Dont forget to provide a Jira Id when triggering the manual action, if no Jira ID is provided the action will not fully succeed. 

After you manually trigger the github action (and it completes with no errors), you must go to [the terra-helmfile](https://github.com/broadinstitute/terra-helmfile) repo and verify that this generated a PR that merged successfully.

The terra-helmfile PR merge will then generate a PR in [leonardo](https://github.com/DataBiosphere/leonardo).  This will automerge if all tests pass, but if jenkins tests fail it will not; be sure to watch it to ensure it merges. To trigger jenkins retest simply comment on PR with "jenkins retest".

2023-07-18 21:48 UTC, davidangb approved these changes

2023-07-19 12:49 UTC, davidangb requested changes
I think this test has issues because the `WDS-integrationTest-LocalFileStorage-input.sql` file we use for restores no longer represents what's in our backups. Specifically, it inserts a row into `sys_wds.instance`. This was on my list of things to fix … I'm gonna see if I can get that done sooner rather than later. Once that's in, I'm curious to see if this test is still a problem.

2023-07-19 14:03 UTC, davidangb commented
I've updated to a representative SQL dump in #311, and pulled in the fixes from here to my PR - I believe #311 supersedes this PR.

2023-07-19 16:31 UTC, yuliadub commented
thank you! I'll just close this one out!

2023-07-19 16:31 UTC, closed without merging