AJ-1591: instance to workspace
DataBiosphere/terra-workspace-data-service pull request #489
Opened 2024-02-02 16:49 UTC by davidangb

draft to iterate on tests, do not review yet

2024-02-06 16:13 UTC, davidangb commented on service/src/test/java/org/databiosphere/workspacedataservice/service/InstanceServiceTest.java
> -  }
moved to `InstanceServiceGetWorkspaceIdTest`

2024-02-06 17:39 UTC, jladieu commented
Without actually looking at the PR yet, I have some existing hunches about your open questions:

1) Trust Liquibase with the job of doing the migration.  Adding a Java layer on top of it could just add bugs.  I think if it is still feeling risky, maybe the way to improve confidence would be to add some Java (Gradle?) tasks that just check the db integrity and assumptions before & after the migration, then exercise them by doing:

```
gradlew db:prechecks
gradlew db:migrate
gradlew db:postcheck
gradlew db:rollback
gradlew db:prechecks
```

BTW, this is based on how I used to test db migrations in Rails...I'm not sure if this maps over to how liquibase migrations work.

2) If your code crashes fast and hard when the nullness constraint is violated, then I think that's all the safety we need. We want to detect issues related to the nullness ASAP rather than letting them propagate through the codebase.  Is it possible to enlist some extra help at compilation time by starting to pull in `@Nullable` and `@NonNull` annotations?

2024-02-06 21:08 UTC, jladieu commented on build.gradle
> +
Ok I happened to be looking back in history for something unrelated, and it looks like we only just introduced the version bump to liquibase as part of upgrading to SpringBoot 3: https://github.com/DataBiosphere/terra-workspace-data-service/pull/440/files

So we haven't been running in a version greater than what you'd need to pin to for very long.  I agree with the hesitation about backsliding, but I think in this case it's not a dramatic reversion.

2024-02-06 21:21 UTC, jladieu commented on build.gradle
> +            dependency 'org.liquibase:liquibase-core:4.21.1'
How do you feel about also documenting this in the service's constraints block, belt & suspenders style, as I've done in similar circumstances: https://github.com/DataBiosphere/terra-workspace-data-service/pull/496/files

2024-02-06 21:22 UTC, jladieu commented on service/src/main/java/org/databiosphere/workspacedataservice/dao/PostgresInstanceDao.java
> +    insertInstanceRow(instanceId, false);
```suggestion
    insertInstanceRow(instanceId, /* ignoreConflict= */ false);
```

2024-02-06 21:23 UTC, jladieu commented on service/src/main/java/org/databiosphere/workspacedataservice/dao/PostgresInstanceDao.java
> +    insertInstanceRow(newSchemaId, true);
```suggestion
    insertInstanceRow(newSchemaId, /* ignoreConflict= */ true);
```

2024-02-06 21:54 UTC, jladieu commented on service/src/main/java/org/databiosphere/workspacedataservice/dao/PostgresInstanceDao.java
> +  private UUID workspaceId;
I think to support the notion that WDS should fail fast if there's anything fishy with `WORKSPACE_ID` the creation of the `PostgresInstanceDao` bean should be `DeploymentMode` aware and strongly enforce the non-null `workspaceId` assumption, perhaps in both directions.

Maybe sibling bean methods somewhere that roughly do the following:

```
@Value("${twds.instance.workspace-id}")
private UUID workspaceId;

@ControlPlane
InstanceDao instanceDao instanceDao() {
    assert(workspaceId == null, "workspaceId must NOT be set in control plane");
    return // new instance of PosgresInstanceDao using the existing single-arg constructor
}

@DataPlane
InstanceDao instanceDao instanceDao() {
    assertLegitWorkspaceId(workspaceId, "workspaceId must legit in the data plane");
    return // new instance of PosgresInstanceDao using an overloaded two-arg constructor with a `@NonNull WorkspaceId` param
}
```

2024-02-06 21:58 UTC, jladieu commented on service/src/main/java/org/databiosphere/workspacedataservice/dao/PostgresInstanceDao.java
> +  private UUID workspaceId;
(or, thinking further on this)...maybe the `InstanceDaoProvider` itself should be the bean, and you get one instance or the other based on the DeploymentMode, and the provider either has (or doesn't have) a `WorkspaceId`?

2024-02-06 22:01 UTC, jladieu commented on service/src/main/java/org/databiosphere/workspacedataservice/dao/PostgresInstanceDao.java
> +  private UUID workspaceId;
Regardless of _how_, I just want to stress the main point which is that it'd be good to fail as early as possible if our assumptions around `WORKSPACE_ID` don't match up with the deploymentMode.

2024-02-06 22:06 UTC, jladieu commented on service/src/main/java/org/databiosphere/workspacedataservice/service/InstanceService.java
> +      // swallow not-found errors; it's valid for rows to not exist in the case of
This might be a good spot to tick a counter if `WORKSPACE_ID` is present, as it would mean a data-plane WDS instance whose instances table hasn't yet been backfilled.  Having this signal drive to (and remain at) zero might help us build confidence that the data migration is complete for all WDS instances past a given version.

2024-02-06 22:14 UTC, jladieu requested changes
After review I think I share your concern about (2) and I think the best way to protect against that is to introduce some kind of mechanism with the bean configuration / construction to crash fast when the `WORKSPACE_ID` assumption != `deploymentMode` assumption.  I offered an idea in the comment but not too hung up on how.

2024-02-06 22:21 UTC, jladieu commented on service/src/main/resources/liquibase/changesets/20240131_add_workspace_to_instance.sql
> +-- finally, set the description, equal to the name
Would you consider leaving description blank?

2024-02-06 22:22 UTC, jladieu commented on service/src/main/resources/liquibase/changesets/20240131_add_workspace_to_instance.yaml
> +        - addNotNullConstraint:
Does description need to be non-null?

2024-02-06 22:34 UTC, yuliadub commented on build.gradle
> +
I dont love the downgrade, but I hate implementing in java way more :D

2024-02-06 22:36 UTC, yuliadub commented on service/src/integrationTest/java/org/databiosphere/workspacedataservice/InstanceInitializerCloneTest.java
> +            "select id, workspace_id, name, description from sys_wds.instance where id = :id",
is there a reason why we need to store name and description of workspace in wds? from my understanding this is something WSM manages but it is likely I am missing some context here

2024-02-06 22:41 UTC, yuliadub commented on service/src/main/resources/liquibase/changesets/20240131_add_workspace_to_instance.yaml
> +        - addNotNullConstraint:
why do we need a description? (it seems like it would always be =name?)

2024-02-06 22:54 UTC, yuliadub commented
> The non-nullness of the workspace_id column requires that the $WORKSPACE_ID env var is populated. This is expected in the Azure data plane today, but was not true in many of our tests and will not be true in GCP. However, we also expect that in GCP control plane, there will be no rows in the sys_wds.instance table, so it's a non-issue. Does this feel safe?

I am struggling with this one - it almost seems like we may want to have a layer above this that will help guide when it is okay to not have a Workspace ID be populated vs not. I dont think I like the concept of overloading workspace id variable in this context. What if we included a new env param that said which environment WDS is being run in (or something equivalent, like control pane vs application pane, or e**ven just renaming the workspace id env variable and containing the value it can be to default or uuid and then basing logic on what to do next based on how we parse it (maybe I like this one best? )** ), that way we can have much more control over what we do at start up (and hopefully prevent cases where things go really wrong since we strongly type what the value can be) 

going to think more about this...will add more notes as more thoughts come

2024-02-12 16:07 UTC, davidangb commented on build.gradle
> +
now using the just-released 4.26.0, which I feel better about.

2024-02-12 21:41 UTC, davidangb commented on service/src/main/java/org/databiosphere/workspacedataservice/dao/PostgresInstanceDao.java
> +  private UUID workspaceId;
As of #509 , all this validation has moved to `StartupConfig`, which should handle validation for InstanceDao as well as any other classes that rely on the `WORKSPACE_ID` value

2024-02-12 21:45 UTC, davidangb commented on service/src/main/resources/liquibase/changesets/20240131_add_workspace_to_instance.yaml
> +        - addNotNullConstraint:
This is all pretty future-looking and speculative. I am picturing being able to refer to a collection _either_ by its UUID, or by the combination of workspaceId + collection name. In such a case, I expect that collection name will be populated in various API signatures as part of an API's path … which means we will likely want to impose some syntax restrictions on the name, e.g. `a-zA-Z0-9\\-_`. And if we impose syntax restrictions on name … we may want a human-readable description. 

Since the code in this PR is the only place we set the name - we don't yet allow end users to set the name - I haven't implemented any syntax restrictions for it yet.

I'm fine leaving the description column out of this PR entirely and only adding it when we need it … would that be preferable?

2024-02-12 22:00 UTC, davidangb commented on build.gradle
> +            dependency 'org.liquibase:liquibase-core:4.21.1'
I don't really like having active code in both places, but I have added a comment in service/build.gradle referencing this change

2024-02-12 22:15 UTC, davidangb commented
@jladieu @yuliadub major changes since you last reviewed:
* Liquibase 4.26.0 is out, and this PR uses it
* #509 added validation of the $WORKSPACE_ID env var at startup, and this PR relies on that
* I believe I have replied to or adopted all feedback

Given all this, I am resetting your reviews, thank you!

2024-02-13 17:37 UTC, jladieu commented on service/src/main/resources/liquibase/changesets/20240131_add_workspace_to_instance.yaml
> +        - addNotNullConstraint:
I have no problem with pre-fetching the description because I think it's a pretty obvious field -- I just don't necessarily think we need to fill it with anything up front as then it becomes something that customers have to clear out if they don't like what it is :)

2024-02-13 17:43 UTC, jladieu commented on service/src/main/java/org/databiosphere/workspacedataservice/dao/PostgresInstanceDao.java
> +        .update(
nit: would you consider extracting an `update` method too?  I like `insertInstanceRow` and think this method's readability would benefit from the update getting the same treatment

2024-02-13 17:46 UTC, jladieu commented on service/src/main/java/org/databiosphere/workspacedataservice/service/InstanceService.java
> +      // swallow not-found errors; it's valid for rows to not exist in the case of
I think the case I was thinking of wouldn't be practical/possible...I was thinking it'd be nice to measure how many unmigrated workspaces exist and watch that inventory go to zero.   But for that to happen, the measurement would have to precede this PR and be installed everywhere already.

So I think my comment is a big no-op.

2024-02-13 18:17 UTC, jladieu approved these changes

2024-02-13 20:35 UTC, davidangb commented on service/src/main/java/org/databiosphere/workspacedataservice/dao/PostgresInstanceDao.java
> +        .update(
I was actively staying away from this, and thought about renaming this existing method to `adoptSchema` or something like that. The current method is only called from the clone/restore path and is not a generic "make changes to a collection" method. We'll need one of those eventually and it should handle name and description too - I'd look to extract reusability at that point.

2024-02-13 21:31 UTC, yuliadub commented on service/src/main/resources/liquibase/changesets/20240131_add_workspace_to_instance.yaml
> +        - addNotNullConstraint:
part of me thinks that we should just add when we have a use case for it, but at the same time, it's just a small column and you already did the work to have it in there, so I'm fine if it stays 😄 (especially if it ends up being null for now)

2024-02-13 21:32 UTC, yuliadub approved these changes
LGTM - thanks for working through this and all the helpful comments!

2024-02-13 22:11 UTC, merged