AJ-1563 Clean up internal APIs
DataBiosphere/terra-workspace-data-service pull request #510
Opened 2024-02-12 21:45 UTC by jladieu

This is prefactoring for [AJ-1563](https://broadworkbench.atlassian.net/browse/AJ-1563).

2024-02-12 21:49 UTC, jladieu commented on service/src/main/java/org/databiosphere/workspacedataservice/service/BatchWriteService.java
> -          List<Record> rList = groupedRecords.get(recType).asList();
Creating a new instance variable `rList` to house the List version of the collection is what tipped me off to start this commit in the first place.  The key change that is unlocked by the refactoring is not having to actually call `asList()` here before passing the collection down.  And the nice thing is that the ordering is still respected later on if the collection ever needs to be iterated on.

2024-02-12 21:52 UTC, jladieu commented on service/src/main/java/org/databiosphere/workspacedataservice/service/BatchWriteService.java
> +        OperationType opType = info.operationType();
BiStream needs to operate on [effectively final](https://www.baeldung.com/java-effectively-final) local variables, which `info` is not because it gets changed by the earlier for loop.  However, the bistream didn't _need_ info and just needed `operationType()` - so doing this assignment here satisfies the requirement by making an effectively final `opType` variable.

2024-02-12 22:08 UTC, nawatts approved these changes

2024-02-12 22:08 UTC, nawatts commented on service/src/main/java/org/databiosphere/workspacedataservice/service/DataTypeInferer.java
> +  Map<String, DataTypeMapping> inferTypes(Collection<Record> records) {
Should this method be marked `VisibleForTesting`? Isn't it used by BatchWriteService?

2024-02-12 22:19 UTC, davidangb commented on service/src/main/java/org/databiosphere/workspacedataservice/dao/RecordDao.java
> +  public void batchDelete(UUID instanceId, RecordType recordType, Collection<Record> records) {
I am a bit hesitant to move from `List` to `Collection`, as these APIs are dependent on ordering of the incoming Records. If a caller used an unordered collection this could result in unexpected results.

2024-02-12 22:32 UTC, davidangb requested changes
:+1: for the refactoring inside `BatchWriteService`.

I don't like moving method signatures from `List` to `Collection`, though, as it suggests that ordering is not relevant - ordering is critical in the input arguments.

2024-02-13 02:51 UTC, jladieu commented on service/src/main/java/org/databiosphere/workspacedataservice/service/DataTypeInferer.java
> +  Map<String, DataTypeMapping> inferTypes(Collection<Record> records) {
Hah, good call...I removed this after all.

This commit ended up being way more underwhelming than I'd hoped...at first I was closing up a bunch of these methods but then realized the leaky part of the API is thus because of its close relationship with `TsvSerializer` which wouldn't let me privatize much at all unfortunately.

2024-02-13 03:21 UTC, jladieu commented on service/src/main/java/org/databiosphere/workspacedataservice/dao/RecordDao.java
> +  public void batchDelete(UUID instanceId, RecordType recordType, Collection<Record> records) {
I punted the commit that switched out `List` for `Collection` although I think I'd still make the case that implicit ordering is sufficient, and in fact, all we can rely on.  As long as we don't mess with the order after it's handed to us we should be good.

I couldn't figure out where the strict ordering mattered in the underlying implementation (which I was squinting at while switching over from `List` -> `Collection`, so I'd like to hear more to better understand.

2024-02-13 12:24 UTC, nawatts commented on service/src/main/java/org/databiosphere/workspacedataservice/dao/RecordDao.java
> +  public void batchDelete(UUID instanceId, RecordType recordType, Collection<Record> records) {
I think because of side effects. For `batchDelete`, I could imagine the order matters if you're trying to delete a referenced record and the record referencing it in the same batch. You'd have to delete the referenced record first.

2024-02-13 14:19 UTC, davidangb commented on service/src/main/java/org/databiosphere/workspacedataservice/dao/RecordDao.java
> +  public void batchDelete(UUID instanceId, RecordType recordType, Collection<Record> records) {
Consider a payload to the `batchWriteRecords` API of:
```json
[
  {
    "operation": "upsert",
    "record": {
      "id": "1",
      "type": "mytype",
      "attributes": {
        "stringAttr": "foo"
      }
    }
  },
  {
    "operation": "upsert",
    "record": {
      "id": "1",
      "type": "mytype",
      "attributes": {
        "stringAttr": "bar"
      }
    }
  }
]
```
After submitting this payload, what would you expect to be the value of the "stringAttr" attribute on record "mytype:1"? Would it be "foo" or "bar"?

2024-02-13 15:04 UTC, davidangb approved these changes
thank you for switching back to `List`, :+1:

2024-02-13 16:28 UTC, jladieu commented on service/src/main/java/org/databiosphere/workspacedataservice/dao/RecordDao.java
> +  public void batchDelete(UUID instanceId, RecordType recordType, Collection<Record> records) {
Thanks for the example and helping me understand!  This makes sense to me...the last one should be recorded last, so "bar".

2024-02-13 16:29 UTC, merged