AJ-1681 - Clean up WDS env variables
DataBiosphere/terra-workspace-data-service pull request #650
Opened 2024-03-14 19:57 UTC by yuliadub

A profile config by default overwrites the contents of what exists in application.yaml if  any of the values collide. This PR removes setting certain variable urls via env vars from the main yaml, and moves that functionality to only be possible only when running a local profile. For all other profiles, hard coded values from the profile config should be used instead. 

Reminder:

PRs merged into main will not automatically generate a PR in https://github.com/broadinstitute/terra-helmfile to update the WDS image deployed to kubernetes - this action will need to be triggered manually by running the following github action: https://github.com/DataBiosphere/terra-workspace-data-service/actions/workflows/tag.yml. Dont forget to provide a Jira Id when triggering the manual action, if no Jira ID is provided the action will not fully succeed. 

After you manually trigger the github action (and it completes with no errors), you must go to [the terra-helmfile](https://github.com/broadinstitute/terra-helmfile) repo and verify that this generated a PR that merged successfully.

The terra-helmfile PR merge will then generate a PR in [leonardo](https://github.com/DataBiosphere/leonardo).  This will automerge if all tests pass, but if jenkins tests fail it will not; be sure to watch it to ensure it merges. To trigger jenkins retest simply comment on PR with "jenkins retest".

2024-03-14 23:22 UTC, jladieu approved these changes

2024-03-18 20:26 UTC, calypsomatic approved these changes

2024-03-18 20:51 UTC, ashanhol commented on service/src/main/resources/application-local.yml
> +leoUrl: ${LEONARDO_URL:https://leonardo.dsde-dev.broadinstitute.org/}
I'm not familiar with this syntax- is this defining $LEONARDO_URL if it's not defined?

2024-03-18 21:52 UTC, yuliadub commented on service/src/main/resources/application-local.yml
> +leoUrl: ${LEONARDO_URL:https://leonardo.dsde-dev.broadinstitute.org/}
it will grab a value from $LEONARDO_URL env variable if it is not empty - but if it is, it will instead make the value "https://leonardo.dsde-dev.broadinstitute.org/"

2024-03-18 22:27 UTC, nawatts commented on service/src/main/java/org/databiosphere/workspacedataservice/SentryInitializer.java
> +  boolean determineIfEnvIsMonitored(String env) {
Super nit, but a few alternative suggestions for function names: 

```suggestion
  boolean isEnvMonitored(String env) {
```
or
```suggestion
  boolean shouldMonitorEnv(String env) {
```

2024-03-18 22:27 UTC, nawatts commented on service/src/main/java/org/databiosphere/workspacedataservice/SentryInitializer.java
> +      env = String.join(",", environment.getActiveProfiles());
It seems like this allows WDS running in local environments, etc. to be configured to use Sentry. Is that actually what we want? It seems like we'd only want Sentry in live environments where `TERRA_ENV` is set?

2024-03-18 22:28 UTC, nawatts commented on service/src/main/java/org/databiosphere/workspacedataservice/SentryInitializer.java
> +  boolean determineIfEnvIsMonitored(String env) {
Alternatively, since the `env` passed is stored in a property of this class, does this method need to take an argument?

2024-03-18 23:10 UTC, yuliadub commented on service/src/main/java/org/databiosphere/workspacedataservice/SentryInitializer.java
> +      env = String.join(",", environment.getActiveProfiles());
I followed the behavior that was there before, but I am also fine with just doing it when TERRA_ENV is set.

2024-03-18 23:11 UTC, yuliadub commented on service/src/main/java/org/databiosphere/workspacedataservice/SentryInitializer.java
> +  boolean determineIfEnvIsMonitored(String env) {
env only exists in the context of the constructor at this time.

2024-03-19 00:19 UTC, ashanhol approved these changes

2024-03-19 13:21 UTC, davidangb requested changes
see comments inline, I am worried this changes how we set tags in Sentry.

2024-03-19 13:21 UTC, davidangb commented on service/src/main/java/org/databiosphere/workspacedataservice/SentryInitializer.java
>                options.setEnvironment(env);
in cases where WDS is started with multiple profiles - which should be always, e.g. "prod,data-plane" - this will set the Sentry "environment" to the full comma-delimited string. This is not ideal - it will will make filtering/classifying issues in Sentry more difficult. I'd much prefer to leave the Sentry "environment" as one of dev|staging|prod, and add any other relevant profiles to their own tags.

My suggestion: use the `sentryEnvironments` List to return a single dev|staging|prod value based on $TERRA_ENV and/or the active profiles, and use that single value to set the Sentry environment. If there are any other profiles you want to include as Sentry tags, add them explicitly as a new tag in the `getTags()` method. Note that we already set a tag of "deploymentMode" for control-plane|data-plane.

It might help to visualize how these are set in the Sentry UI:
![Screenshot 3-19-2024 at 09 08 AM (1)](https://github.com/DataBiosphere/terra-workspace-data-service/assets/6041577/ffc0e415-7a0a-4b03-a137-4a6e0c0113cd)

2024-03-19 13:21 UTC, davidangb commented on service/src/main/java/org/databiosphere/workspacedataservice/SentryInitializer.java
> +      env = String.join(",", environment.getActiveProfiles());
I believe $TERRA_ENV is only set in the control plane, so the else clause that inspects `environment.getActiveProfiles()` is useful for the data plane.

2024-03-19 13:21 UTC, davidangb commented on service/src/main/java/org/databiosphere/workspacedataservice/SentryInitializer.java
> +      env = String.join(",", environment.getActiveProfiles());
In the else clause that calls `environment.getActiveProfiles()`, this turns the String array into a comma-delimited string, and later in determineIfEnvIsMonitored you're checking for substrings of that comma-delimited string. This breaks if a profile value itself contains a comma (which we don't have now, admittedly). I'd prefer to leave the data as an array, e.g.

```java
    String[] envs;
    if (StringUtils.isNotBlank(terraEnv)) {
      envs = new String[]{terraEnv};
    } else {
      envs = environment.getActiveProfiles();
    }
```
and
```java
  boolean determineIfEnvIsMonitored(String[] envs) {
    for (var env : envs) {
      if (sentryEnvironments.contains(env)) {
        return true;
      }
    }
    return false;
  }
```

You'd have to modify the `options.setEnvironment(…)` call too, but I think that's necessary - see my other comment

2024-03-19 16:42 UTC, yuliadub commented on service/src/main/java/org/databiosphere/workspacedataservice/SentryInitializer.java
> +      env = String.join(",", environment.getActiveProfiles());
getActiveProfiles() actually reads the comma and returns it as a string[] without the comma from my testing, but I totally understand the tagging of env in Sentry being a comma separated list being an issue. Let me know if this revised way looks better

2024-03-19 16:44 UTC, yuliadub commented on service/src/main/java/org/databiosphere/workspacedataservice/SentryInitializer.java
>        env = terraEnv;
is it okay to trust TerraEnv here or would we still need to check if this is set to prod/staging/dev?

2024-03-19 18:07 UTC, davidangb commented on service/src/main/java/org/databiosphere/workspacedataservice/SentryInitializer.java
>        env = terraEnv;
We should still check if this is set to prod/staging/dev. `terraEnv` here can/will also reflect BEEs, but we don't want BEEs to send to Sentry to keep noise down.

2024-03-19 18:16 UTC, jladieu approved these changes
I had an idea of how to tidy up some of the logic around sentryEnvironment using an `Optional`, but...the suggestion is, itself...entirely _optional_ if you just want to ship this :)

2024-03-19 18:16 UTC, jladieu commented on service/src/main/java/org/databiosphere/workspacedataservice/SentryInitializer.java
> +        return profile;
```suggestion
        return Optional.of(profile);
```

2024-03-19 18:16 UTC, jladieu commented on service/src/main/java/org/databiosphere/workspacedataservice/SentryInitializer.java
> +    return "";
```suggestion
    return Optional.empty();
```

2024-03-19 18:16 UTC, jladieu commented on service/src/main/java/org/databiosphere/workspacedataservice/SentryInitializer.java
> +  String getSentryEnvironment(String[] profiles) {
```suggestion
  Optional<String> getSentryEnvironment(String[] profiles) {
```

Would you consider returning an `Optional<String>` here?  I'll add some suggestions here and where it's called for how it might look.

2024-03-19 18:16 UTC, jladieu commented on service/src/main/java/org/databiosphere/workspacedataservice/SentryInitializer.java
> +              options.setDsn(env != "" ? dsn : "");
```suggestion
              options.setDsn(getSentryEnvironment(environment.getActiveProfiles()).orElse("");
```

2024-03-19 18:16 UTC, jladieu commented on service/src/main/java/org/databiosphere/workspacedataservice/SentryInitializer.java
>      if (StringUtils.isNotBlank(terraEnv)) {
If you like my suggestion to use an `Optional<String>` for `getSentryEnvironment` and want to incorporate it, then I think it might make sense to hide the `terraEnv` check shortcut in that method and drop this if/else here in this method entirely.

2024-03-19 22:30 UTC, nawatts approved these changes

2024-03-19 22:30 UTC, nawatts commented on service/src/main/java/org/databiosphere/workspacedataservice/SentryInitializer.java
> +              options.setDsn(!env.equals(DEFAULT_ENV) ? dsn : "");
Nit: this could be simplified by swapping the branches.

```suggestion
              options.setDsn(env.equals(DEFAULT_ENV) ? "" : dsn);
```

2024-03-19 22:30 UTC, nawatts commented on service/src/test/java/org/databiosphere/workspacedataservice/SentryInitializerTest.java
>      /* Arguments are pairs of input Sam URL and expected environment parsed from that URL
This comment is out of date.

2024-03-20 13:19 UTC, davidangb approved these changes
yay thank you!

2024-03-20 17:51 UTC, davidangb approved these changes

2024-03-20 18:00 UTC, merged