AJ-1726 Add measurement to `processStatusUpdate`
DataBiosphere/terra-workspace-data-service pull request #697
Opened 2024-04-01 16:45 UTC by jladieu

For [AJ-1726](https://broadworkbench.atlassian.net/browse/AJ-1726):  Add measurement to `processStatusUpdate`.

Commits have been intentionally broken apart for easier review if needed.

Introduces two new measures:
- `wds.job.update` is the time it takes to update a job in the database
- `wds.job.elapsed` is the time elapsed since the job was created

Also changes the `jobType` label values of `wds.job.execute` to use the value from `JobKey`

2024-04-01 18:25 UTC, nawatts requested changes
I think `JobDao` would be a preferable place for these metrics than `JobService.processStatusUpdate`. The issue with `JobService.processStatusUpdate` is that it _only_ handles status updates sent from Rawls via PubSub. So it only applies to a subset of status updates on the control plane.

2024-04-01 18:25 UTC, nawatts commented on service/src/test/java/org/databiosphere/workspacedataservice/jobexec/QuartzJobTest.java
> +        .hasLowCardinalityKeyValue("jobType", "jobGroup")
Super nit: I think a different name would make it more obvious that this is a placeholder value for tests.

```suggestion
        .hasLowCardinalityKeyValue("jobType", "testJobType")
```

2024-04-01 18:26 UTC, jladieu commented on service/src/test/java/org/databiosphere/workspacedataservice/service/JobServiceTest.java
> +class JobServiceTest extends JobServiceTestBase {
The `processStatusUpdate` tests were moved into this test file so all those tests existed previously.  New tests start at `processJobStatusUpdateMeasuresDurationSinceCreationOnSuccess` and continue to the end of the file.

As noted in one of the refactoring commits, the stubbing logic for these tests was adjusted slightly to make it easier to add more customization to the stubbed job.

2024-04-01 18:28 UTC, jladieu commented on service/src/main/java/org/databiosphere/workspacedataservice/jobexec/QuartzJob.java
> +            .lowCardinalityKeyValue("jobType", jobKey.getGroup())
This is a key change which caused a new set of labels to get used for `jobType`.  I'm doing this here because later on at the end of the job processing (during `processStatusUpdate`) we no longer have the class name in hand to use to label the metrics.  I think it's important to have the metrics labeled consistently, so wanted to use something that was accessible in both places.  The `jobInput` stores this information and it's available later on.

2024-04-01 18:29 UTC, jladieu commented on service/src/main/java/org/databiosphere/workspacedataservice/dao/QuartzSchedulerDao.java
> -    JobDetail jobDetail =
Pushing this logic into `Schedulable` makes it easier to reuse in tests and reduce the drift of test code from production code.

2024-04-01 19:38 UTC, jladieu commented
>I think JobDao would be a preferable place for these metrics than JobService.processStatusUpdate. The issue with JobService.processStatusUpdate is that it only handles status updates sent from Rawls via PubSub. So it only applies to a subset of status updates on the control plane.

Can you say more?  Are there other mechanisms where we update status in control plane?  I do ideally want to catch them all, but I also think pushing this down a layer into `JobDao` may bring with it some tradeoffs I'd want to think about more.

2024-04-01 19:45 UTC, ashanhol commented on service/src/main/java/org/databiosphere/workspacedataservice/jobexec/QuartzJob.java
> +            .lowCardinalityKeyValue("jobType", jobKey.getGroup())
Where does a job key's group get set? Will this be a unique value or just a generic thing for all jobs?

2024-04-01 19:45 UTC, jladieu commented on service/src/test/java/org/databiosphere/workspacedataservice/jobexec/QuartzJobTest.java
> +        .hasLowCardinalityKeyValue("jobType", "jobGroup")
Fixed with 9f7851bc71801c8d27803e5ffd418fb5f1c0e785

2024-04-01 19:46 UTC, ashanhol commented on service/src/main/java/org/databiosphere/workspacedataservice/service/ImportService.java
> +      case PFB -> new PfbSchedulable(jobId.toString(), "PFB import", arguments);
are pfb imports ready to go? not sure if this was something that should have been removed and wasn't, it's kind of weird to take out a todo for this on a metrics PR otherwise

2024-04-01 19:47 UTC, nawatts commented
The status updates from Rawls would only be transitions from Running to either Succeeded or Errored. There are several other states.
https://github.com/DataBiosphere/terra-workspace-data-service/blob/98e2b157631ade98ae40805b4cf4ad59525e171e/service/src/main/java/org/databiosphere/workspacedataservice/generated/GenericJobServerModel.java#L76-L88

But more than that, what about the data plane?

2024-04-01 19:49 UTC, jladieu commented on service/src/main/java/org/databiosphere/workspacedataservice/shared/model/Schedulable.java
> +        .withIdentity(new JobKey(id, group))
@ashanhol this is where the `group` gets set into the JobKey which gets used for the `jobType` metric.  The group is passed in as the first arg of creating the `Schedulable` in the subclasses: [PfbSchedulable](https://github.com/DataBiosphere/terra-workspace-data-service/blob/main/service/src/main/java/org/databiosphere/workspacedataservice/dataimport/pfb/PfbSchedulable.java#L12) and [TdrManifestSchedulable](https://github.com/DataBiosphere/terra-workspace-data-service/blob/98e2b157631ade98ae40805b4cf4ad59525e171e/service/src/main/java/org/databiosphere/workspacedataservice/dataimport/tdr/TdrManifestSchedulable.java#L13)

2024-04-01 19:50 UTC, jladieu commented on service/src/main/java/org/databiosphere/workspacedataservice/jobexec/QuartzJob.java
> +            .lowCardinalityKeyValue("jobType", jobKey.getGroup())
It's a couple steps of indirection, I added a comment over where the group gets set: https://github.com/DataBiosphere/terra-workspace-data-service/pull/697/files#r1546779365 and that breadcrumbs to where it _actually_ gets set to either `TDRMANIFEST` or `PFB`

2024-04-01 19:51 UTC, ashanhol commented on service/src/main/java/org/databiosphere/workspacedataservice/service/JobService.java
> +      throw e;
what other exceptions would we expect? could you leave a comment if there's a new scenario to anticipate?

2024-04-01 19:51 UTC, davidangb commented
Consider for instance an import job with some invalid input, which fails early. That job will move to failed state via `getJobDao().fail()`, here:

https://github.com/DataBiosphere/terra-workspace-data-service/blob/98e2b157631ade98ae40805b4cf4ad59525e171e/service/src/main/java/org/databiosphere/workspacedataservice/jobexec/QuartzJob.java#L87

2024-04-01 19:53 UTC, jladieu commented on service/src/main/java/org/databiosphere/workspacedataservice/service/ImportService.java
> +      case PFB -> new PfbSchedulable(jobId.toString(), "PFB import", arguments);
I assumed its removal was just something we missed.

Looking at git history, I think this TODO was put in a long time ago (sixish months) when @davidangb was first introducing the quartz job stuff.  It strongly predates the PFB work which is mostly wrapped at this point.

2024-04-01 19:55 UTC, ashanhol commented on service/src/test/java/org/databiosphere/workspacedataservice/dataimport/pfb/PfbTestUtils.java
> +    var schedulable =
do we use `var`s? Everything's been strongly typed that I've seen so I was under the impression this teams coding standards shied away from vars (but I could have just assumed wrong)

2024-04-01 19:58 UTC, ashanhol commented on service/src/main/java/org/databiosphere/workspacedataservice/shared/model/Schedulable.java
> +        .withIdentity(new JobKey(id, group))
Thank you!

2024-04-01 20:05 UTC, jladieu commented on service/src/test/java/org/databiosphere/workspacedataservice/service/JobServiceTest.java
> +      "data-plane", // need _a_ profile even if this test only contains tests for common behavior
Fixed in 643d2f44f4d5eccab0eaf5840a7439afc2d5bb5c

2024-04-01 20:21 UTC, jladieu commented on service/src/main/java/org/databiosphere/workspacedataservice/service/JobService.java
> +      throw e;
Added an explanatory comment in f7b4fcae8a09f4d167416cdd8d9d9d6e74361262

I wanted to make sure that any exception thrown out of the wrapped logic would correctly mark the observation with the error, including the exceptions thrown explicitly in the try block.  I didn't have any other categories of exception in mind besides those though.

2024-04-02 14:13 UTC, jladieu commented
Switching this back to draft while I move the observation logic down to the Dao.  I might end up with another PR to replace this one instead.

2024-04-02 21:32 UTC, jladieu commented
Replaced with https://github.com/DataBiosphere/terra-workspace-data-service/pull/699

2024-04-02 21:32 UTC, closed without merging